#Create a new service principal
$sp = New-AzADServicePrincipal -Scope /subscriptions/<azure_subscription_id>

#Display the names of the service principal
$sp.ServicePrincipalNames
# ServicePrincipalName = 92149ed8-b640-4a4d-a22f-9411c293668a

#Display the autogenerated password as text
$UnsecureSecret = ConvertFrom-SecureString -SecureString $sp.Secret -AsPlainText
# $UnsecureSecret = 85b2e416-c8d2-46a9-a636-1da8a1aa4e76


#Log in to Azure using a service principal
#Get a PsCredential object using one of the following techniques.
#Method 1: Call Get-Credential and enter a service principal name and password when requested
$spCredential = Get-Credential

#Method 2: Construct a PsCredential object in memory
$spName = "<service_principal_name>" 
$spPassword = ConvertTo-SecureString "<service_principal_password>" -AsPlainText -Force
$spCredential = New-Object System.Management.Automation.PSCredential($spName , $spPassword)

#Call Connect-AzAccount, passing the PsCredential object.
Connect-AzAccount -Credential $spCredential -Tenant "<azure_subscription_tenant_id>" -ServicePrincipal

#Install azure CLI as well before working with terraform
#----------------------------------------------------------------------------
#Create a Terraform configuration file

#Create a directory to hold the Terraform files for this demo
mkdir QuickstartTerraformTest

#Change directories to the demo directory
cd QuickstartTerraformTest

#Using your favorite editor, create a Terraform configuration file
code QuickstartTerraformTest.tf

#-----------------------------------------------------------------------
#Create and apply a Terraform execution plan

#Initialize the Terraform deployment with terraform init.
#This step downloads the Azure modules required to create an Azure resource group.
terraform init

#Run terraform plan to create an execution plan from your Terraform configuration file.
terraform plan -out QuickstartTerraformTest.tfplan

#Run terraform apply to apply the execution plan.
terraform apply QuickstartTerraformTest.tfplan

#Once the execution plan is applied, you can test that the resource group was successfully created using Get-AzResourceGroup.
Get-AzResourceGroup -Name QuickstartTerraformTest-rg

#------------------------------------------------------------------------
#Clean up resources
#Run terraform plan to create an execution plan to destroy the 
#resources indicated in the Terraform configuration file.
terraform plan -destroy -out QuickstartTerraformTest.destroy.tfplan

#Run terraform apply to apply the execution plan
terraform apply QuickstartTerraformTest.destroy.tfplan

#Verify that the resource group was deleted by using Get-AzResourceGroup.
Get-AzResourceGroup -Name QuickstartTerraformTest-rg